spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qadb
    username: qauser
    password: qapass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 6001

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.indium: INFO
    org.hibernate.SQL: INFO
    org.hibernate.tool.schema: INFO
