spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: devuser
    password: devpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 6000

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.indium: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
